name: deploy
on:
  push:
    branches:
    - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: docker://vapor/swift:5.1-xenial
      with:
        entrypoint: swift
        args: test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: vapor/action/deploy@master
      env: 
        VAPOR_CLOUD_TOKEN: ${{ secrets.VAPOR_CLOUD_TOKEN }}
      with:
        app: sound-white-22429
        env: production
        branch: master
